name: SLSA Go releaser
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: |
          go build -v ./...
      - name: Run tests
        run: |
          go test -v ./...
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qalx-binaries
          path: |
            **/*.exe
            **/*.out
            **/*.bin
            **/*.a
            **/*.so
            **/*.dll
            **/*.dylib
            **/*.test
            core/*.go
            examples/*.go
            tests/*.go
